### ISSUE TITLE
FFRK Inspector hangs Fiddler on /dff/get_init_battle_data

### ISSUE THREAD

**Issue by ph33rtehgd** [Spirialis/FFRKInspector#2]
It looks like the /dff/get_init_battle_data call is causing Fiddler to hang. I raised this to you in a PM on reddit, and thought the issue was due to not having the database credentials setup. At first I thought it was resolved, but it came back a few days later. Here is the Fiddler log of events below. You can see the hang happens here:

21:01:09:4811 FFRKInspector: /dff/event/wday/607/get_battle_init_data
21:01:09:9045 FFRKInspector: dff.sp.mbga.jp:443
21:02:49:9063 FFRKInspector: dff.sp.mbga.jp:443

When it freezes up I can see the get_battle_init_data is the last call in the Fiddler window and I cannot interact with Fiddler for about a minute and a half to two minutes. During this time other network calls will timeout.

Full log:

21:00:46:0474 FFRKInspector: /dff/party_memory/save
21:00:47:7597 FFRKInspector: /favicon.ico
21:00:48:0321 FFRKInspector: /dff/relation/detailed_fellow_listing
21:00:52:9772 FFRKInspector: /dff/relation/find_by_user_ids
21:00:55:1217 FFRKInspector: /dff/event/wday/607/enter_dungeon
21:00:56:0723 FFRKInspector: /favicon.ico
21:00:56:3703 FFRKInspector: /dff/world/battles
21:00:56:3829 FFRKInspector: Database thread dequeued request of type DbOpRecordBattleList
21:00:56:3829 FFRKInspector: Database exceuting operation DbOpVerifySchema
21:00:56:3829 FFRKInspector: An error occurred executing request DbOpVerifySchema.  Message = Object reference not set to an instance of an object..
   at FFRKInspector.Database.FFRKMySqlInstance.EnsureConnected()
   at FFRKInspector.Database.FFRKMySqlInstance.ProcessDbRequestOnThisThread(IDbRequest Request)
21:00:56:3829 FFRKInspector: Database exceuting operation DbOpRecordBattleList
21:00:56:3829 FFRKInspector: An error occurred executing request DbOpRecordBattleList.  Message = Object reference not set to an instance of an object..
   at FFRKInspector.Database.FFRKMySqlInstance.EnsureConnected()
   at FFRKInspector.Database.FFRKMySqlInstance.ProcessDbRequestOnThisThread(IDbRequest Request)
21:00:56:3829 FFRKInspector: Database thread waiting for request
21:00:56:3868 FFRKInspector: Database thread dequeued request of type DbOpFilterDrops
21:00:56:3868 FFRKInspector: Database exceuting operation DbOpVerifySchema
21:00:56:3868 FFRKInspector: An error occurred executing request DbOpVerifySchema.  Message = Object reference not set to an instance of an object..
   at FFRKInspector.Database.FFRKMySqlInstance.EnsureConnected()
   at FFRKInspector.Database.FFRKMySqlInstance.ProcessDbRequestOnThisThread(IDbRequest Request)
21:00:56:3868 FFRKInspector: Database exceuting operation DbOpFilterDrops
21:00:56:3868 FFRKInspector: An error occurred executing request DbOpFilterDrops.  Message = Object reference not set to an instance of an object..
   at FFRKInspector.Database.FFRKMySqlInstance.EnsureConnected()
   at FFRKInspector.Database.FFRKMySqlInstance.ProcessDbRequestOnThisThread(IDbRequest Request)
21:00:56:3868 FFRKInspector: Database thread waiting for request
21:00:56:3888 FFRKInspector: Database thread dequeued request of type DbOpFilterDrops
21:00:56:3888 FFRKInspector: Database exceuting operation DbOpVerifySchema
21:00:56:3888 FFRKInspector: An error occurred executing request DbOpVerifySchema.  Message = Object reference not set to an instance of an object..
   at FFRKInspector.Database.FFRKMySqlInstance.EnsureConnected()
   at FFRKInspector.Database.FFRKMySqlInstance.ProcessDbRequestOnThisThread(IDbRequest Request)
21:00:56:3888 FFRKInspector: Database exceuting operation DbOpFilterDrops
21:00:56:3888 FFRKInspector: An error occurred executing request DbOpFilterDrops.  Message = Object reference not set to an instance of an object..
   at FFRKInspector.Database.FFRKMySqlInstance.EnsureConnected()
   at FFRKInspector.Database.FFRKMySqlInstance.ProcessDbRequestOnThisThread(IDbRequest Request)
21:00:56:3888 FFRKInspector: Database thread waiting for request
21:01:04:1392 FFRKInspector: /dff/event/wday/607/begin_battle_session
21:01:04:4649 FFRKInspector: /dff/event/wday/607/begin_battle
21:01:05:4473 FFRKInspector: /dff/battle/?timestamp=1527728465&battle_id=1006071301
21:01:05:7509 FFRKInspector: /favicon.ico
21:01:06:9460 FFRKInspector: /favicon.ico
21:01:09:4811 FFRKInspector: /dff/event/wday/607/get_battle_init_data
21:01:09:9045 FFRKInspector: dff.sp.mbga.jp:443
21:02:49:9063 FFRKInspector: dff.sp.mbga.jp:443
21:03:09:6518 FFRKInspector: /dff/event/wday/607/win_battle
21:03:39:7303 FFRKInspector: /dff/event/wday/607/win_battle
21:04:11:3162 FFRKInspector: /dff/event/wday/607/win_battle
21:04:29:7995 FFRKInspector: Database thread dequeued request of type DbOpRecordBattleEncounter
21:04:29:7995 FFRKInspector: Database exceuting operation DbOpVerifySchema
21:04:29:8004 FFRKInspector: An error occurred executing request DbOpVerifySchema.  Message = Object reference not set to an instance of an object..
   at FFRKInspector.Database.FFRKMySqlInstance.EnsureConnected()
   at FFRKInspector.Database.FFRKMySqlInstance.ProcessDbRequestOnThisThread(IDbRequest Request)
21:04:29:8004 FFRKInspector: Database exceuting operation DbOpRecordBattleEncounter
21:04:29:8004 FFRKInspector: An error occurred executing request DbOpRecordBattleEncounter.  Message = Object reference not set to an instance of an object..
   at FFRKInspector.Database.FFRKMySqlInstance.EnsureConnected()
   at FFRKInspector.Database.FFRKMySqlInstance.ProcessDbRequestOnThisThread(IDbRequest Request)
21:04:29:8004 FFRKInspector: Database thread waiting for request

**Comment by ph33rtehgd** [comment]
If I stop the proxy within the Windows settings I get the below exception from Fiddler. I'm guess that this is the call that's hanging as it's what was active when I killed off the proxy.

System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.GetResponse()
   at FFRKInspector.UI.FFRKViewEnemyDetails.PopulateEnemyInfoGroupBox(EventBattleInitiated battle)
   at FFRKInspector.UI.FFRKViewEnemyDetails.comboBoxEnemySelection_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at FFRKInspector.UI.FFRKViewEnemyDetails.PopulateEnemySelectionComboBox(EventBattleInitiated battle)
   at FFRKInspector.UI.FFRKViewEnemyDetails.<>c__DisplayClass17_0.<FFRKProxy_OnBattleEngaged>b__0()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
